### ISSUE TITLE
Get-NixLog

### ISSUE THREAD

**Issue by StartAutomating** [StartAutomating/PowerNix#7]
We should have a command to Get-NixLogs.

It should handle several different log formats, and use the first line / name of the log to detect which format to use.

It should also be "smart aliased", so that calling it with a well-known log name will get results from that log (e.g. sys.log)

It would be nice to provide some filtering parameters, though these should probably be limited.

**Comment by joshcorr** [comment]
I can take a look at this.

**Comment by joshcorr** [comment]
I have been think about this a bit, and I think that we should do the following

Create `Get-NixLog`
- Use journalctl to get and filter logs as this supports a json format which will make it easier to convert to an object.
- Standard across supported versions of Linux where PowerShell would be installed

Create `Get-NixLogFile`
- For older logs that may be based on rsyslog format of logs.
- This will be a little more string/text manipulation but should be doable because it is in a standard format.

**Comment by StartAutomating** [comment]
How about we expose it as Get-NixLog and Get-NixLog -LogFile ? (or some such switch)

Basically the default parameter set would use journalctl, and the -LogFile switch would make it return the fileinfo.

What do you think?

**Comment by joshcorr** [comment]
That works as well. Will start with the journalctl portion.

**Comment by StartAutomating** [comment]
👍
